### ISSUE TITLE
Proof of Concept Plan + Demo 

### ISSUE THREAD

**Issue by littleappledev** [sgao1995/Cat-and-Mouse-Game#14]
(Notes from Meeting #1) 
-  Investigate FEASIBILITY
- Identify RISKS

Dates:

26 October 2016:   Proof of Concept Plan (Course Deliverable)
Week of 21 November 2016:  Proof of Concept Demostration (Course Deliverable)

**Comment by smiths** [comment]
Hello James.  I have three quick suggestions:
1. Use hash tags (#) to identify other issues.  When you say #1, GitLab automatically creates a link to issue #1.  This is a nice feature, but confusing since you meant the first meeting, not the first issue.
2. For larger tasks, like prepare for the proof of concept demonstration, you would probably be better off creating a milestone, as opposed to an issue.  Issues are better if they are something that can be assigned to a specific person and then that person can close the issue relatively quickly.  Assigning someone the task of identifying risks would be more appropriate for an issue.
3. Try to make the issues "atomic."  Your issue include the proof of concept plan and the proof of concept demo.  It is easier to manage closing issues when they are separated.

**Comment by littleappledev** [comment]
Hi Dr Smith,

Thank you for letting me know! I shall put this as  a seperate milestone within the project so that there is a seperation of concerns and it is easier to close Issues as suggested.

**Comment by littleappledev** [comment]
This Issue has been migrated to a Milestone as and will therefore be marked as Closed. Please see above for a link to the Issues which pertain to this Milestone.
